version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      PORT: 8080
      ENVIRONMENT: LOCALHOST
      GOOGLE_APPLICATION_CREDENTIALS: /usr/src/app/secrets/google-appengine-credentials.json
    ports:
      - 9080:8080
    volumes:
      - .:/usr/src/app
    command: api/entrypoint-dev.sh

  cron:
    build:
      context: .
      dockerfile: cron/Dockerfile
    environment:
      PORT: 8080
      ENVIRONMENT: LOCALHOST
      GOOGLE_APPLICATION_CREDENTIALS: /usr/src/app/secrets/google-appengine-credentials.json
    ports:
      - 9090:8080
    volumes:
      - .:/usr/src/app
    command: cron/entrypoint-dev.sh

  frontend:
    build:
      dockerfile: frontend/Dockerfile
      context: .
    tty: true
    environment:
      PORT: 3000
    ports:
      - 4000:3000
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c "cd /usr/src/app && cp src/Config.localhost.js src/Config.js && npm ci && npm start && wait $$"

