version: '3.3'

services:
#  Application

#  Infrastructure
  redis:
    build:
      context: redis
      dockerfile: Dockerfile
    ports:
      - "5010:6379"
    volumes:
      - ./data/redis:/data

  mongo:
    image: mongo:4.4-bionic
    ports:
      - "5011:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/mongodb:/data/db

  mongo-express:
    image: mongo-express:0.54
    ports:
      - "5012:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_BASICAUTH_USERNAME: ''
      ME_CONFIG_BASICAUTH_PASSWORD: ''
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_PORT: "27017"
      ME_CONFIG_MONGODB_SERVER: 'mongo'
      ME_CONFIG_OPTIONS_EDITORTHEME: 'default'
      ME_CONFIG_REQUEST_SIZE: '100kb'
      ME_CONFIG_SITE_BASEURL: '/'
