version: '3.3'

services:
  api:
    image: ghcr.io/klaasjanelzinga/newsrooom/api:ee08907b391731bd46bdfd95e91cc4d393b6e361
    env_file:
      - etc/dev.env

  cron:
    image: ghcr.io/klaasjanelzinga/newsrooom/cron:ee08907b391731bd46bdfd95e91cc4d393b6e361
    env_file:
      - etc/dev.env

  frontend:
    image: ghcr.io/klaasjanelzinga/newsrooom/frontend:ee08907b391731bd46bdfd95e91cc4d393b6e361
    tty: true
    environment:
      PORT: 3000

  nginx:
    image: ghcr.io/klaasjanelzinga/newsrooom/nginx:ee08907b391731bd46bdfd95e91cc4d393b6e361
#    build:
#      context: infra/nginx
    ports:
      - "80:80"

  mongo:
    image: ghcr.io/klaasjanelzinga/newsrooom/mongo:ee08907b391731bd46bdfd95e91cc4d393b6e361
#    build:
#      context: infra/mongo
    env_file:
      - etc/dev.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASS
      MONGO_INITDB_USERNAME: $MONGO_USER
      MONGO_INITDB_PASSWORD: $MONGO_PASS
      MONGO_INITDB_DATABASE: $MONGO_DB
    volumes:
      - ./infra/data/mongodb-live:/data/db
