version: '3.3'

services:
  api:
    image: ghcr.io/klaasjanelzinga/newsrooom/api:${VERSION}
    ports:
      - "127.0.0.1:9001:5001"
    env_file:
      - etc/production.env

  cron:
    image: ghcr.io/klaasjanelzinga/newsrooom/cron:${VERSION}
    ports:
      - "127.0.0.1:9002:5002"
    env_file:
      - etc/production.env

  frontend:
    image: ghcr.io/klaasjanelzinga/newsrooom/frontend:${VERSION}
    depends_on:
      - api
    tty: true
    env_file:
      - etc/production.env
    ports:
      - "127.0.0.1:9000:3000"
    environment:
      PORT: 3000

networks:
  default:
    name: infranetwork
    external: true
