name: Deploy application
on:
  push:
    branches:
      - main
jobs:
  build:
    name: test-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build the python docker image
        run: scripts/build-docker-images.sh --version $GITHUB_SHA
      - name: Verify the build
        run: docker run --env ENVIRONMENT=LOCALHOST -v `pwd`:/usr/src/app newsrooom/unittests:latest
      - name: Deploy the app
        run: scripts/deploy.sh --version $GITHUB_SHA api frontend cron
