name: Run tests
on:
  push:
    branches-ignore:
      - main
jobs:
  build:
    name: make-docker-image-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build the python docker image
        run: scripts/build-docker-images.sh --version $GITHUB_SHA
      - name: Verify the build
        run: make run-tests-in-docker
