name: Run tests
on:
  push:
    branches-ignore:
      - main
jobs:
  build:
    name: make-docker-image-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Login docker
        run: echo $GH_PACKAGES_PAT | docker login ghcr.io -u klaasjanelzinga@me.com --password-stdin
      - name: Build the python docker image
        run: scripts/build-docker-images.sh --version $GITHUB_SHA
      - name: Decrypt the test env file
        run: scripts/decrypt-test-env-file.sh
      - name: Verify the build
        run: make run-tests-in-docker
